name: Docker CI/CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/docker-atelier

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Générer le tag de version
        id: vars
        run: |
          # Si on est sur un tag git (v1.2.3) -> on l'utilise
          # Sinon -> short SHA du commit
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          else
            echo "TAG=sha-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build de l'image (local, pas encore push)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Scan de vulnérabilités avec Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}
          format: table
          exit-code: '1'          # fait échouer le job si vulnérabilité trouvée
          ignore-unfixed: true    # ignore les CVE sans fix dispo
          severity: 'CRITICAL'

      - name: Login Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push de l'image sur Docker Hub
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}
            ${{ env.IMAGE_NAME }}:latest
